main.name = "Pwnagotchi"
main.lang = "en"
main.confd = "/etc/pwnagotchi/conf.d/"
main.custom_plugins = ""
main.custom_plugin_repos = [
  "https://github.com/evilsocket/pwnagotchi-plugins-contrib/archive/master.zip"
]
main.iface = "mon0"
main.mon_start_cmd = "/usr/bin/monstart"
main.mon_stop_cmd = "/usr/bin/monstop"
main.mon_max_blind_epochs = 5
main.no_restart = false
main.whitelist = ['home-wifi-name', 'example2',]
main.filter = ""

[main.log]
debug = false
path = "/var/log/pwnagotchi.log"

[main.log.rotation]
enabled = true
size = "10M"

[main.plugins.automatic-updates]
enabled = true
repo = "ex18a/pwnagotchi64"
interval = 6
install = true

[main.plugins.grid]
enabled = true
report = true

[main.plugins.watchdog]
enabled = true

[main.plugins.portrait-mode]
enabled = true

[main.plugins.IPDisplay]
enabled = true

[main.plugins.hashvault]
enabled = true

[main.plugins.dev-ai-trained]
enabled = true

[main.plugins.pisugar3i2c]
enabled = true
low_battery_shutdown_pct = 10

[main.plugins.face_only]
enabled = false

[main.plugins.wpa-sec]
enabled = false
api_key = ""
api_url = "https://wpa-sec.stanev.org"
download_results = true
download_interval = 3600
whitelist = []

[main.plugins.memtemp]
enabled = true
scale = "celsius"
orientation = "horizontal"

[ai]
enabled = true
path = "/root/brain.nn"
laziness = 0.2
epochs_per_episode = 10

[ai.params]
gamma = 0.99
n_steps = 1
vf_coef = 0.25
ent_coef = 0.01
max_grad_norm = 0.5
learning_rate = 0.001
rms_prop_eps = 0.00001
verbose = 1

[personality]
advertise = false
deauth = true
associate = true
channels = []
min_rssi = -75
ap_ttl = 240
sta_ttl = 300
recon_time = 150
max_inactive_scale = 3
recon_inactive_multiplier = 2
hop_recon_time = 30
min_recon_time = 15
max_interactions = 4
max_misses_for_recon = 6
excited_num_epochs = 3
bored_num_epochs = 4
sad_num_epochs = 6
bond_encounters_factor = 20000
home_absent_epochs = 5
ai_wake_epochs = 2
environment_change_threshold = 0.5
wifi_hop_period_ms = 1000
action_throttle = 0.5

[ui]
fps = 0.0
cursor = true
cursor_interval = 3

[ui.font]
name = "DejaVuSansMono"
size_offset = 0

[ui.faces]
look_r = ["( ⚆_⚆)", "( ◕_◕)"]
look_l = ["(☉_☉ )", "(◕_◕ )"]
look_r_happy = ["( ◕‿◕)", "( ≧◡≦)"]
look_l_happy = ["(◕‿◕ )", "(≧◡≦ )"]
sleep = "(⇀‿‿↼)"
sleep2 = ["(≖‿‿≖)", "(≖__≖)", "(u__u)", "(-__-)", "(z__z)", "(◡__◡)"]
awake = "(◕‿‿◕)"
bored = "(-__-)"
intense = ["(°▃▃°)", "( ◣_◢)"]
cool = ["(⌐■_■)", "(♥‿‿♥)"]
happy = ["(•‿‿•)", "(^‿‿^)", "(^◡◡^)"]
excited = ["(ᵔ◡◡ᵔ)", "(✜‿‿✜)"]
grateful = "(^‿‿^)"
motivated = "(☼‿‿☼)"
demotivated = "(≖__≖)"
smart = "(✜‿‿✜)"
lonely = "(ب__ب)"
sad = "(╥☁╥ )"
angry = "(-_-')"
friend = ["(♥‿‿♥)", "(♡‿‿♡)", "(♥‿♥ )", "(♥ω♥ )"]
broken = "(☓‿‿☓)"
debug = "(#__#)"
upload = "(1__0)"
upload1 = "(1__1)"
upload2 = "(0__1)"

[ui.web]
enabled = true
address = "0.0.0.0"
auth = false
username = "pwnagotchi"
password = "pwnagotchi"
origin = ""
port = 8080
on_frame = ""

[ui.display]
enabled = true
rotation = 0
type = "waveshare_4"
color = "black"
full_refresh_every = 300

[bettercap]
scheme = "http"
hostname = "localhost"
port = 8081
username = "pwnagotchi"
password = "pwnagotchi"
handshakes = "/home/pwn/handshakes"
silence = [
  "ble.device.new",
  "ble.device.lost",
  "ble.device.disconnected",
  "ble.device.connected",
  "ble.device.service.discovered",
  "ble.device.characteristic.discovered",
  "wifi.client.new",
  "wifi.client.lost",
  "wifi.client.probe",
  "wifi.ap.new",
  "wifi.ap.lost",
  "mod.started"
]

[fs.memory]
enabled = false

[fs.memory.mounts.log]
enabled = false
mount = "/var/log"
size = "50M"
sync = 60
zram = true
rsync = true

[fs.memory.mounts.data]
enabled = false
mount = "/var/tmp/pwnagotchi"
size = "10M"
sync = 3600
zram = false
rsync = true
